### PR TITLE
Special ordering of homepage sponsor logos

### LINKED ISSUE #244: sort sponsor logos on the main page (bottom)
The sponsor logos need to be sorted in order of :
the ones that sponsored more than others go to top and are sorted by number of sponsorships of events
and the most recent sponsors

### PR DESCRIPTION
**Pull request by tonymarklove**
- Current event sponsors first followed by everyone else
- Within those two groups, sponsors of more events will appear higher

Closes #244

### CODE REVIEW

**Comment by maloneyl** [comment]
From reading the issue, I thought we wanted the sponsors with the most sponsorships first, and then within sponsors with the same number of sponsorships, sort them based on how recent their last sponsored event was? Or maybe that interpretation was clouded based on how I would've presented the sponsors...

**Comment by tonymarklove** [comment]
I wasn't exactly sure on the interpretation of the issue.

It seems slightly odd to me that we would show ex-sponsors at all, so I
thought putting current sponsors first made sense. But we can tweak the
ordering pretty easily if someone (Maria?) confirms what we want.

**Comment by hundred** [comment]
lets keep it the way you ve done Tony, but one thing would cause a problem , could you please change it:
if there is no @next_event it will throw errors, so maybe just add an if condition there?

**Comment by tonymarklove** [comment]
Good catch. That is now protected against.

**Comment by hundred** [comment]
👍

**Pull request merged**
